apiVersion: 1

datasources:
  - name: AI Gateway Postgres
    uid: ai-gateway-postgres
    type: postgres
    access: proxy
    url: ai-gateway-postgres:5432
    user: $POSTGRES_USER
    database: $POSTGRES_DB
    isDefault: true
    jsonData:
      sslmode: disable
      postgresVersion: 1600
      timescaledb: false
    secureJsonData:
      password: $POSTGRES_PASSWORD
